### ISSUE TITLE
Highlight Changes to Sample Code

### ISSUE THREAD

**Issue by pricetd1024** [PacktPublishing/Swift-5-Cookbook-Second-Edition#2]
I have found the book to be very informative and interesting. However, one issue I have with the print version is that it is difficult to follow changes in the code as you progress through the chapter. I found myself having to visually scan the code blocks (sometimes more than once), to make sure I didn't miss anything. It would be convenient if you could highlight the parts that changed, perhaps using bolding, underscore, or another color (if possible).

**Comment by sonam-packt** [comment]
Hi @pricetd1024,

Firstly, we are glad that you found the book interesting and informative.

Thank you for the suggestion, will discuss it with the team and will try to add this to our further book.

Thanks,
Sonam
