### ISSUE TITLE
Some Chapter 5 Errata

### ISSUE THREAD

**Issue by pricetd1024** [PacktPublishing/Swift-5-Cookbook-Second-Edition#3]
First, the url provided in the text version is incorrect; it includes 'Swift-Cookbook-5-Second-Edition' but the actual url omits the '-5'. Also, in the There's More section, you twice wrote Result<..., Error? instead of Result<..., Error>. You've probably already acted on these, but just in case.

**Comment by Maran9** [comment]
Hi,
Thanks for pointing these errata's out much appreciated
